#!/bin/bash
#
# LNiF MRI Lab Pipeline for preprocessing of
# structural and functional MRI dataset
# stefano.tambalo@unitn.it - 20200310
#
# Preprocess functional EPI timeseries:
# -   Drop 10 volumes
# -   Grand Mean Scaling
# -   Realignment and estimation of motion parameters
# -   Detection of motion outliers for temporal masking
#
########################################################################
export LC_ALL=C

shopt -s extglob
Usage() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "\tFSLDIR not set!\n\n"
    printf "\tRequires:\n\t\tFSL (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSL)\n"
    printf "\n\n(c) stefano.tambalo@unitn.it, 2020.\n"
    printf "***************************************************\n\n"
    exit 1
}

Start() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "Process functional data (motion correction)\n"    

}

NextStep() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "Complete. Exec. Time: ${exectime}\nNow run lnifmri_prep03_sdc"
    printf "\n\n***************************************************\n\n"
    exit 1
}

[ "$FSLDIR" = "" ] && Usage
exectime=0
SECONDS=0

Start

for SUBDIR in sub-*[0-9] ; do
#cd ${subdir}
#echo $SUBDIR
    for epiimg in `$FSLDIR/bin/imglob $SUBDIR/func/*ep2d_bold*[0-9]_+([0-9]).nii.gz` ; do

        epiname=`$FSLDIR/bin/remove_ext ${epiimg}`
        scanname=`basename ${epiimg}`

        printf "\tDataset: ${epiname}\n"

        #Extract core parameters from JSON
        TR=$(cat ${epiname}.json | sed 's/.*"RepetitionTime": \(.*\),.*/\1/;t;d')

        #Store multiband slice timing extracted from JSON
        cat ${epiname}.json | \
        tr -d '\n\t' | \
        sed 's/.*"SliceTiming": \[\([^]]*\)\].*/\1/g' | \
        tr ',' '\n' > $SUBDIR/func/${scanname}_slicetiming.txt;

        #Next steps are self-explanatory
        printf "\tDiscarding first 10 vols\n"
        $FSLDIR/bin/fslroi $epiimg $epiimg 10 150

        printf "\tSetting data type\n"
        $FSLDIR/bin/fslmaths $epiimg $epiimg -odt float 

        printf "\tGrand Mean scaling\n"
        $FSLDIR/bin/fslmaths $epiimg -ing 1000 $epiimg

        printf "\tSlice Timing correction\n"
        $FSLDIR/bin/slicetimer  -i $epiimg \
                                -o $epiimg \
                                --odd -r $TR \
                                --tcustom=$SUBDIR/func/${scanname}_slicetiming.txt;

        printf "\tMotion Correction\n"
        $FSLDIR/bin/mcflirt -in $epiimg \
                            -out $epiimg \
                            -meanvol \
                            -mats -plots \
                            -rmsrel -rmsabs \
                            -spline_final;
        #Plot motion traces
        $FSLDIR/bin/fsl_tsplot  -i $SUBDIR/func/${scanname}.par \
                                -t 'MCFLIRT estimated rotations (radians)' \
                                -u 1 --start=1 --finish=3 -a x,y,z -w 640 -h 144 \
                                --ymin=-0.01 --ymax=0.01 \
                                -o $SUBDIR/func/${scanname}_rot.png;
        #Plot motion traces
        $FSLDIR/bin/fsl_tsplot  -i $SUBDIR/func/${scanname}.par \
                                -t 'MCFLIRT estimated translations (mm)' \
                                --ymin=-1 --ymax=1 \
                                -u 1 --start=4 --finish=6 -a x,y,z -w 640 -h 144 \
                                -o $SUBDIR/func/${scanname}_tra.png;

        printf "\tDetecting motion outliers\n\n"
        $FSLDIR/bin/fsl_motion_outliers -i $epiimg \
                                        -o $SUBDIR/func/${scanname}_motout.txt \
                                        -s $SUBDIR/func/${scanname}_motoutdvars.txt \
                                        --dvars --nomoco;
        #Plot motion traces
        $FSLDIR/bin/fsl_tsplot  -i $SUBDIR/func/${scanname}_motoutdvars.txt \
                                -t 'Motion Outlier Metric: dvars' \
                                -a out -w 640 -h 144 \
                                --ymin=0 --ymax=100 \
                                -o $SUBDIR/func/${scanname}_motout.png;                                    
    done #${epiname}
done #for .sub
duration=$SECONDS
printf -v exectime "$(($duration / 60))m:$(($duration % 60))s."
NextStep