#!/bin/bash
#
# LNiF MRI Lab Pipeline for preprocessing of
# structural and functional MRI dataset
# stefano.tambalo@unitn.it - 20200310
#
# Generation of utility files and report for visual QC
#
########################################################################
export LC_ALL=C

shopt -s extglob


# INDEX page
printf "<HTML>\n<HEAD><TITLE>lnifmri_prep Report</TITLE></HEAD>\n<BODY>\n" >> ${QCDIR}/index.html
printf "<OBJECT data=head.html></OBJECT>\n" >> ${QCDIR}/index.html
printf "<IFRAME  height=80px width=100% src=nav.html frameborder=0></IFRAME><p>\n" >> ${QCDIR}/index.html
printf "<b>Analysis methods</b> <br>\n" >> ${QCDIR}/index.html
printf "Insert Description Here\n" >> ${QCDIR}/index.html
printf "<b>References</b> <br>\n" >> ${QCDIR}/index.html
printf "<HR><CENTER><FONT SIZE=1>This page produced automatically by lnifmri_prep</FONT></CENTER>\n" >> ${QCDIR}/index.html
printf "</BODY></HTML>\n" >> ${QCDIR}/index.html

# HEADER page
printf "<TABLE BORDER=0>\n<TR>\n" >> ${QCDIR}/head.html
printf "<TD ALIGN=CENTER WIDTH=100%>\n" >> ${QCDIR}/head.html
printf "<TABLE BORDER=0>\n" >> ${QCDIR}/head.html
printf "<tr>\n<td align=center><font size=+3><b>lnifmri_prep QC Report</b>\n" >> ${QCDIR}/head.html
printf "</font><tr><td valign=center align=center> <p>\n" >> ${QCDIR}/head.html
printf "<br>Date/Time: %s" "${stamp}\n" >> ${QCDIR}/head.html
printf "</tr>\n" >> ${QCDIR}/head.html
printf "<tr valign=bottom><td align=center>\n" >> ${QCDIR}/head.html
printf "</tr></table>\n" >> ${QCDIR}/head.html
printf "<TD ALIGN=RIGHT>\n" >> ${QCDIR}/head.html
#printf "<a href=http://LINKCIMEC target=_top>" >> ${QCDIR}/lnifmri_prep_head.html
#printf "<IMG BORDER=0 SRC=file:LOGOCIMEC.jpg WIDTH=165></a>" >> ${QCDIR}/lnifmri_prep_head.html
#printf "</TD>" >> ${QCDIR}/lnifmri_prep_head.html
printf "</TR></TABLE> <hr>\n" >> ${QCDIR}/head.html

# MENU bar
printf "<CENTER><TABLE BORDER=0><TR>\n" >> ${QCDIR}/nav.html
printf "<TD ALIGN=CENTER WIDTH=100%><FONT SIZE=-1>\n" >> ${QCDIR}/nav.html
printf "<A HREF="${QCDIR}/index.html" target="_top">Index</A>&nbsp;-&nbsp;<A HREF="${QCDIR}/pars.html" target="_top">ACQParameters</A>&nbsp;-&nbsp;<A HREF="${QCDIR}/mot.html "target="_top">MotionCorrection</A>&nbsp;-&nbsp;<A HREF="${QCDIR}/reg.html "target="_top">Registration</A>&nbsp;-&nbsp;<A HREF="${QCDIR}/pspec.html "target="_top">PowerSpectrum</A></FONT></TD>\n" >> ${QCDIR}/nav.html
printf "</TR></TABLE></CENTER><hr>\n" >> ${QCDIR}/nav.html

# PARAMETERS REPORT page
printf "<style type="text/css">OBJECT { width: 100% }</style><TITLE>lnifmri_prep</TITLE></HEAD>\n" >> ${QCDIR}/pars.html
printf "<IFRAME  height=50px width=100% src=nav.html frameborder=0></IFRAME><BR>\n" >> ${QCDIR}/pars.html
printf "<Center>\n" >> ${QCDIR}/pars.html
printf "<a href="${QCDIR}/index.html">&#60;</a>&nbsp;-&nbsp;<a href="${QCDIR}/mot.html">&#62;</a><p><H3>Acquisistion Parameters<br></b></H3><hr><p>\n" >> ${QCDIR}/pars.html
printf "<img BORDER=0 SRC="${QCDIR}/lnifmri_prep_acqparam_QC.png" ALT="ACQP Report"></A><p>\n" >> ${QCDIR}/pars.html
printf "<HR><CENTER><FONT SIZE=1>This page produced automatically by lnifmri_prep</FONT></CENTER>\n" >> ${QCDIR}/pars.html
printf "</BODY></HTML>\n" >> ${QCDIR}/pars.html

# MOTION REPORT page
printf "<style type="text/css">OBJECT { width: 100% }</style><TITLE>lnifmri_prep</TITLE></HEAD>\n" >> ${QCDIR}/mot.html
printf "<IFRAME  height=50px width=100% src=nav.html frameborder=0></IFRAME><BR>\n" >> ${QCDIR}/mot.html
printf "<Center>\n" >> ${QCDIR}/mot.html
printf "<a href="${QCDIR}/pars.html">&#60;</a>&nbsp;-&nbsp;<a href="${QCDIR}/pspec.html">&#62;</a><p><H3>Acquisistion Parameters<br></b></H3><hr><p>\n" >> ${QCDIR}/mot.html
printf "<img BORDER=0 SRC="${QCDIR}/lnifmri_prep_motion_QC.png" ALT="ACQP Report"></A><p>\n" >> ${QCDIR}/mot.html
printf "<HR><CENTER><FONT SIZE=1>This page produced automatically by lnifmri_prep</FONT></CENTER>\n" >> ${QCDIR}/mot.html
printf "</BODY></HTML>\n" >> ${QCDIR}/mot.html

# POWER SPECTRUM REPORT page
printf "<style type="text/css">OBJECT { width: 100% }</style><TITLE>lnifmri_prep</TITLE></HEAD>\n" >> ${QCDIR}/pspec.html
printf "<IFRAME  height=50px width=100% src=nav.html frameborder=0></IFRAME><BR>\n" >> ${QCDIR}/pspec.html
printf "<Center>\n" >> ${QCDIR}/pspec.html
printf "<a href="${QCDIR}/mot.html">&#60;</a>&nbsp;-&nbsp;<a href="${QCDIR}/index.html">&#62;</a><p><H3>Acquisistion Parameters<br></b></H3><hr><p>\n" >> ${QCDIR}/pspec.html
printf "<img BORDER=0 SRC="${QCDIR}/lnifmri_prep_pspec_QC.png" ALT="ACQP Report"></A><p>\n" >> ${QCDIR}/pspec.html
printf "<HR><CENTER><FONT SIZE=1>This page produced automatically by lnifmri_prep</FONT></CENTER>\n" >> ${QCDIR}/pspec.html
printf "</BODY></HTML>\n" >> ${QCDIR}/pspec.html
