#!/bin/bash
#
# LNiF MRI Lab
#
# Deploy updated version of lnifmri_prep
#
# stefano.tambalo@unitn.it - 20210514
#
########################################################################

# Header
########################################################################
export LC_ALL=C
shopt -s extglob

#Deploy to mriserver
#rsync -aP ~/Documents/bin/lnifmri* stefano.tambalo@mri-server.cimec.unitn.it:/home/stefano.tambalo/Documents/bin
#rsync -aP ~/Documents/bin/lnifmri* /media/stefano/mumi-data001/USERS/Stefano_Tambalo/lnifmri_bin
rsync -aP ~/Documents/bin/lnifmri* stefano.tambalo@mri-server.cimec.unitn.it/opt/lnifmri_prep/bin

#Deploy to Tettamanti workstation
rsync -aP ~/Documents/bin/lnifmri_prep* ~/Documents/bin/lnifmri_anat ~/Documents/bin/lnifmri_epi_reg blg@192.168.176.25:/mnt/disk2/mrphmri/mrphmri_batchfiles
rsync -aP ~/Documents/bin/lnifmri_util* ~/Documents/bin/lnifmri_anat ~/Documents/bin/lnifmri_epi_reg blg@192.168.176.25:/mnt/disk2/mrphmri/mrphmri_batchfiles