#!/bin/bash
#
# LNiF MRI Lab Pipeline for preprocessing of
# structural and functional MRI dataset
# stefano.tambalo@unitn.it - 20200310
#
# Screening of JSON files from functional EPI timeseries to list
# -   TR
# -   TE
# -   BW
# -   EchoSpacing
# -   Slice Num
# -   Fat Sat
# -   MB factor
# -   Volumes
# to identify possible inconsistencies
#
########################################################################

shopt -s extglob
Usage() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "\tFSLDIR not set!\n\n"
    printf "\tRequires:\n\t\tFSL (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSL)\n"
    printf "\n\n(c) stefano.tambalo@unitn.it, 2020.\n"
    printf "***************************************************\n\n"
    exit 1
}

Start() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "Process functional data (m)\n"    

}

NextStep() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "Complete. Exec. Time: ${exectime}\nNow run lnifmri_prep03_sdc"
    printf "\n\n***************************************************\n\n"
    exit 1
}

[ "$FSLDIR" = "" ] && Usage
exectime=0
SECONDS=0
QCDIR=`pwd`/qc

Start

declare -a fields=( "RepetitionTime" \
                    "EchoTime" \
                    "PixelBandwidth" \
                    "DerivedVendorReportedEchoSpacing" \
                    "MultibandAccelerationFactor");
declare -A pars
declare -A numpars

subcount=0

for SUBDIR in sub-*[0-9] ; do
#cd ${subdir}
#echo $SUBDIR
    for epiimg in `$FSLDIR/bin/imglob $SUBDIR/func/lnifmri_prep_files/*ep2d_bold*[0-9]_+([0-9]).nii.gz` ; do

        epiname=`$FSLDIR/bin/remove_ext ${epiimg}`
        scanname=`basename ${epiimg}`

        #printf "\tDataset: ${epiname}\n"

        for f in "${!fields[@]}" ; do
            
            str="s|.*"\"${fields[$f]}\"": \(.*\),.*|\1|;t;d"
            #echo "$str"
            pars[$f]=$(cat ${epiname}.json | sed "${str}") # >> ${QCDIR}/cacca.txt
            #echo ${pars[$f]}
            numpars[$f]=`cksum <<< ${pars[$f]} | cut -f 1 -d ' '`
            printf "${pars[$f]}\t" >> ${QCDIR}/qc_screen_rawfunc.txt
            printf "${numpars[$f]}\t" >> ${QCDIR}/qc_screen_func.txt            

        done

        printf "\n" >> ${QCDIR}/qc_screen_rawfunc.txt
        printf "\n" >> ${QCDIR}/qc_screen_func.txt
        printf "1\n" >> ${QCDIR}/qc_screen_design.txt

    done #${epiname}

    printf "[%2s]\t%s\t\n" "$(( ++subcount ))" "${SUBDIR}" >> ${QCDIR}/qc_screen_rows.txt

done #for .sub

# ################ ONLY FOR TESTING PURPOSE #########################################
# ###################################################################################
dTR=1.1
dTE=0.032
dBW=2237
dES=0.00061
dMB=8
dTRc=`cksum <<< ${dTR} | cut -f 1 -d ' '`
dTEc=`cksum <<< ${dTE} | cut -f 1 -d ' '`
dBWc=`cksum <<< ${dBW} | cut -f 1 -d ' '`
dESc=`cksum <<< ${dES} | cut -f 1 -d ' '`
dMBc=`cksum <<< ${dMB} | cut -f 1 -d ' '`

printf "${dTRc}\t${dTEc}\t${dBWc}\t${dESc}\t${dMBc}\n" >> ${QCDIR}/qc_screen_func.txt
printf "1\n" >> ${QCDIR}/qc_screen_design.txt
# ####################################################################################
# ####################################################################################

$FSLDIR/bin/fsl_glm -i ${QCDIR}/qc_screen_func.txt \
                    -d ${QCDIR}/qc_screen_design.txt \
                    -o ${QCDIR}/qc_screen_out.txt \
                    --out_res=${QCDIR}/qc_screen_res.txt

awk '{ if (NR==1) { n = split($0, a, " "); } for (i=1; i<n; i++) { printf("%.3f\t", ($i/a[i])); } printf("%.3f\n", ($n/a[n])); }' ${QCDIR}/qc_screen_res.txt > ${QCDIR}/qc_screen_resnorm.txt

#Replace NaN values
sed -i 's/-nan/1/g' ${QCDIR}/qc_screen_resnorm.txt 

for p in "${!fields[@]}"; do
#Plot motion traces
    l=$((${p}+1))
    title=${fields[$p]}
    $FSLDIR/bin/fsl_tsplot  -i ${QCDIR}/qc_screen_resnorm.txt \
                       	    -t ${title} \
                       	    -u 1 -w 640 -h 144 \
                            --start=${l} --finish=${l} \
                       	    --ymin=-3 --ymax=3 \
                       	    -o ${QCDIR}/lnifmri_prep_screenpars_${fields[p]}_func_QC.png;
done

duration=$SECONDS
printf -v exectime "$(($duration / 60))m:$(($duration % 60))s."

printf "Code\tSub-ID\t" >> ${QCDIR}/qc_screen_headers.txt
printf "\nKey to param headers:\n" >> ${QCDIR}/qc_screen_keyheaders.txt    
for f in "${fields[@]}" ; do
    
    hdr=$(echo "${f}" | tr -dc '[:upper:]')
    printf "${hdr}\t" >> ${QCDIR}/qc_screen_headers.txt
    printf "%s\t%s\n" "${hdr}" "${f}" >> ${QCDIR}/qc_screen_keyheaders.txt    

done
printf "\n" >> ${QCDIR}/qc_screen_headers.txt

paste -d " " ${QCDIR}/qc_screen_rows.txt ${QCDIR}/qc_screen_rawfunc.txt > ${QCDIR}/qc_screen_table.txt
cat ${QCDIR}/qc_screen_headers.txt ${QCDIR}/qc_screen_table.txt > ${QCDIR}/qc_screen_display.txt
cat ${QCDIR}/qc_screen_keyheaders.txt | sed 's/\t/,|,/g' | column -s ',' -t
printf "\n"
cat ${QCDIR}/qc_screen_display.txt | sed 's/\t/,|,/g' | column -s ',' -t


NextStep