#!/bin/bash
#
# LNiF MRI Lab Pipeline for preprocessing of
# structural and functional MRI dataset
# stefano.tambalo@unitn.it - 20200310
#
# Generation of utility files and report for visual QC
#
########################################################################
export LC_ALL=C

shopt -s extglob

UsageFSL() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "\tFSLDIR not set!\n\n"
    printf "\tRequires:\n\t\tFSL (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSL)\n"
    printf "\n\n(c) stefano.tambalo@unitn.it, 2020.\n"
    printf "***************************************************\n\n"
    exit 1
}

Start() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "Build QC reports (registration, motion correction, power spectrum)\n"        
}

NextStep() {
    printf "Complete. Exec. Time: ${exectime}"
    printf "\n\n***************************************************\n\n"
    exit 1
}

[ "$FSLDIR" = "" ] && UsageFSL
exectime=0
SECONDS=0
pnglist=""
QCDIR=`pwd`/qc
stamp=`date +'%T'`

#legend="fmp,tup,unc"

Start

# for SUBDIR in sub-*[0-9] ; do
for SUBDIR in `cat qc/lnifmri_prep_inputlist.txt` ; do

	#printf "$SUBDIR\n"
	fs="fmp,"
	ts="tup,"
	us="unc"

	#Load EPI scan
	for epiimg in `ls -d1 ${SUBDIR}/func/*ep2d_bold*[0-9]_+([0-9]).nii.gz`; do
	    
		scanname=`basename ${epiimg}`
		epiname=`$FSLDIR/bin/remove_ext ${epiimg}`
		rot=${epiname}_rot.png
		tra=${epiname}_tra.png

		#Compose a single-subject motion report
		if [ -f ${epiname}_motout.txt ]; then
			mot=${epiname}_motout.png
			printf -v str  "%s + %s + %s" "$mot" "$tra" "$rot" 
        	[[ -z "$pnglist" ]] && pnglist="${pnglist} ${str}" || pnglist="${pnglist} - ${str}"
		else
			#Create an empty placeholder to keep consistent layout of report
			printf "${SUBDIR}: Motion outliers not found! Preparing a placeholder\n"
			k=`$FSLDIR/bin/fslval ${epiimg} dim4`
			#printf '0\n%.0s' {1..$k} > $SUBDIR/func/placeholder_motout.txt
			awk -v i=$k 'BEGIN { OFS="0\n"; $i="0"; print }' > $SUBDIR/func/placeholder_motout.txt
		    $FSLDIR/bin/fsl_tsplot  -i $SUBDIR/func/placeholder_motout.txt \
		                    	    -t 'Motion Outliers not detected' \
        		                    -a out -w 640 -h 144 \
                		            --ymin=0 --ymax=100 \
                        	    	-o $SUBDIR/func/placeholder_motout.png;
       		mot=$SUBDIR/func/placeholder_motout.png
			printf -v str  "%s + %s + %s" "$mot" "$tra" "$rot" 
	        [[ -z "$pnglist" ]] && pnglist="${pnglist} ${str}" || pnglist="${pnglist} - ${str}"
		fi
	done #for epiimg
	#Prepare placeholder for powerspectrum in case some options are missing (FMP, TUP or both)
	if [ ! -d $SUBDIR/func/sdc_fmp ]; then
		fs="xxx,"
		printf "${SUBDIR}: FMP power spectrum not found! Preparing a placeholder\n"
		mkdir $SUBDIR/func/sdc_fmp_placeholder 
		awk -v i=$d 'BEGIN { OFS="0\n"; $i="0"; print }' > $SUBDIR/func/sdc_fmp_placeholder/placeholder_spectrum.txt
	fi
	if [ ! -d $SUBDIR/func/sdc_tup ]; then
		ts="xxx,"
		printf "${SUBDIR}: TUP power spectrum not found! Preparing a placeholder\n"		
		mkdir $SUBDIR/func/sdc_tup_placeholder 
		awk -v i=$d 'BEGIN { OFS="0\n"; $i="0"; print }' > $SUBDIR/func/sdc_tup_placeholder/placeholder_spectrum.txt
	fi
	
	#Compose label for charts
	printf -v lbl "${fs}${ts}${us}"
	
	#Merge spectra files and plot a subject-wise overlay
    paste -d " " `ls -d1 ${SUBDIR}/func/sdc_*/*_spectrum.txt` > $QCDIR/qc_${SUBDIR}_pspectra.txt
	d=$(cat $QCDIR/qc_${SUBDIR}_pspectra.txt | wc -l )
	nyq=$(echo "0.5/2/${d}" | bc -l)
    
	$FSLDIR/bin/fsl_tsplot  -i $QCDIR/qc_${SUBDIR}_pspectra.txt \
							-u ${nyq} \
 							-y "Power" -x "Frequency (Hz)" \
	                  	    -t "${SUBDIR} Power Spectra" \
 	   	                    -a ${lbl} -w 640 -h 144 \
 	   	                    --ymin=0 --ymax=500000 \
 	   	                    --start=1 --finish=3 \
 	       		            -o $QCDIR/qc_${SUBDIR}_pspectra.png;
	
	paste -d " " `ls -d1 ${SUBDIR}/func/*_motout.txt` > $QCDIR/qc_global_motout.txt
done #for SUBDIR

#Merge motion outliers temporal masks and plot a group report
# awk '{for(i=1;i<=NF;i++)x+=$i;print x;x=0}' $QCDIR/qc_global_motout.txt > $QCDIR/qc_sum_motout.txt
# $FSLDIR/bin/fsl_tsplot	-i $QCDIR/qc_sum_motout.txt\
# 						-t 'Summary of Motion Outliers'\
# 						-a sum -w 640 -h 144 \
#                         -o $QCDIR/qc_summary_motout.png;
# pnglist="$pnglist ${QCDIR}/qc_summary_motout.png"

#Create final plot (motion)                       
$FSLDIR/bin/pngappend ${pnglist} $QCDIR/lnifmri_prep_motion_QC.png
#Create final plot (power spectrum)
printf -v pspeclist "$( ls -d1 ${QCDIR}/*pspectra.png | sed ':a;N;$!ba;s/\n/ - /g' )"
$FSLDIR/bin/pngappend ${pspeclist} $QCDIR/lnifmri_prep_pspec_QC.png

#Create filelist for group-ICA in MNI space
ls -d1 `pwd`/sub*/func/sdc_fmp/*MNI-smooth.nii.gz > $QCDIR/filelist-groupICA-fmp.txt
ls -d1 `pwd`/sub*/func/sdc_tup/*MNI-smooth.nii.gz > $QCDIR/filelist-groupICA-tup.txt
ls -d1 `pwd`/sub*/func/sdc_unc/*MNI-smooth.nii.gz > $QCDIR/filelist-groupICA-unc.txt

#Create filelist for VBM
ls -d1 `pwd`/sub*/anat/*t1_*rage*[0-9]_+([0-9]).nii.gz > $QCDIR/filelist-VBM-template.txt

#Clean up subject folder
for SUBDIR in sub-* ; do
	mkdir -p ${SUBDIR}/func/lnifmri_prep_files
	ls -d1 ${SUBDIR}/func/*.* > ${SUBDIR}/func/${SUBDIR}_filelist.txt
	xargs mv -t ${SUBDIR}/func/lnifmri_prep_files/ < ${SUBDIR}/func/${SUBDIR}_filelist.txt
done

#Clean up QC folder 
mkdir -p $QCDIR/lnifmri_prep_qcfiles
mv $QCDIR/qc_*.txt $QCDIR/lnifmri_prep_qcfiles/
mv $QCDIR/qc_*.png $QCDIR/lnifmri_prep_qcfiles/

#Create some utility files for the HTML report

# Conversion list raw subj-name -> sub-XX
printf "%s ->\n" `ls -d1 ../*.sub` > ${QCDIR}/lnifmri_prep_qcfiles/qc_screen_rawsubs.txt
paste ${QCDIR}/lnifmri_prep_qcfiles/qc_screen_rawsubs.txt ${QCDIR}/lnifmri_prep_qcfiles/qc_screen_subs.txt > ${QCDIR}/lnifmri_prep_qcfiles/qc_screen_rawtosubs.txt

# List to populate registration gallery to std
ls -d1 ${QCDIR}/lnifmri_prep_func2std_QC/*sub-*.png > ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostd_images.txt
for s in `cat ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostd_images.txt`; do
	case "${s}" in
		*fmap*)
			printf "%s(fmp)\n" `grep -oP "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostd_captions.txt
		;;
		*tup*)
			printf "%s(tup)\n" `grep -oP "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostd_captions.txt
		;;
		*unc*)
			printf "%s(unc)\n" `grep -oP "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostd_captions.txt
		;;
	esac
done
paste -d "|" ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostd_images.txt ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostd_captions.txt > ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostd_media.txt
awk	-F \| '
	{printf "<div class=\"container\">\n\t<img src=\"%s\" alt=\"Reg2Std\" class=\"responsive\">\n\t<div class=\"top-left\">%s</div>\n</div>\n", $1, $2}' \
	${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostd_media.txt > ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostd.txt

# List to populate registration gallery to struc 
ls -d1 ${QCDIR}/lnifmri_prep_func2struc_QC/*sub-*.png > ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc_images.txt
for s in `cat ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc_images.txt`; do
	case "${s}" in
		*fmap*)
			printf "%s(fmp)\n" `grep -oP -m 1 "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc_captions_temp.txt
		;;
		*tup*)
			printf "%s(tup)\n" `grep -oP -m 1 "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc_captions_temp.txt
		;;
		*unc*)
			printf "%s(unc)\n" `grep -oP -m 1 "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc_captions_temp.txt
		;;
	esac
done
uniq ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc_captions_temp.txt > ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc_captions.txt
paste -d "|" ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc_images.txt ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc_captions.txt > ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc_media.txt
awk	-F \| '
	{printf "<div class=\"container\">\n\t<img src=\"%s\" alt=\"Reg2Std\" class=\"responsive\">\n\t<div class=\"top-left\">%s</div>\n</div>\n", $1, $2}' \
	${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc_media.txt > ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc.txt



# Create an HTML report
cat << EOR > ${QCDIR}/lnifmri_prep_report.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box}

body, html {
  height: 100%;
  margin: 0;
  font-family: "Courier New", Courier, monospace;
}

.header {
  padding: 20px;
  text-align: center;
  background: #555;
  color: white;
  font-size: 24px;
}

img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}

#navbar {
  overflow: hidden;
  background-color: #555;
}

.sticky {
  position: fixed;
  top: 0;
  width: 100%;
}

.content {
  padding: 16px;
}

.sticky + .content {
  padding-top: 60px;
}

.tablink {
  background-color: #555;
  color: white;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  font-size: 18px;
  width: 16.66%;
  display: table-cell;
}

.tablink:hover {
  background-color: #777;
}

.tabcontent {
  color: black;
  display: none;
  padding: 20px 20px;
  padding-top: 50px;
  height: 100%;
}

.responsive {
	width: 100%;
	height: auto;
}

.footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: #555;
  color: white;
  text-align: center;
}

.column {
  float: left;
  width: 50%;
  padding: 25px 100px 50px;
  margin: auto;
}

.row:after {
  content: "";
  display: table;
  clear: both;
}

@media screen and (max-width: 600px) {
  .column {
    width: 100%;
  }

.container {
  display: flex;
  flex-wrap: wrap;
  padding: 0 4px;
  position: relative;
  text-align: center;
  color: white;
}

/* Top left text */
.top-left {
  position: absolute;
  top: 8px;
  left: 16px;
}

/* Solid border */
hr.solid {
  border-top: 3px solid #555;
}

</style>
</head>
<body>

<div class="header">
  <h1>lnifmri_prep</h1>
  <p>Quality Control Report</p>
</div>

<div id="navbar">
<button class="tablink" onclick="openPage('REP', this, 'white')" id="defaultOpen">REPORT</button>
<button class="tablink" onclick="openPage('ACQ', this, 'white')">ACQP</button>
<button class="tablink" onclick="openPage('MNI', this, 'white')">MNI</button>
<button class="tablink" onclick="openPage('T1w', this, 'white')">T1w</button>
<button class="tablink" onclick="openPage('MOT', this, 'white')">MOTCO</button>
<button class="tablink" onclick="openPage('PWR', this, 'white')">PWR</button>
</div>

<!--
<hr class="solid">
-->

<div id="REP" class="tabcontent">
<br>
  <p style="text-align: center;"><b>Output dir</b>: $(pwd); <b>Timestamp</b>: ${stamp}</p>
 <br>
 <div class="row">
 	<div class="column">
  		<h2>List of Available Subjects:</h2>
  		<pre>$(cat ${QCDIR}/lnifmri_prep_qcfiles/qc_screen_rawtosubs.txt)</pre>
	</div>
  	<div class="column">
  		<h2>List of Processed Subjects:</h2>
  		<pre>$(cat ${QCDIR}/lnifmri_prep_inputlist.txt)</pre>
	</div>
 </div>
 <div class="row">
  	<div class="column">
  		<h2>Summary of Acq. Parameters:</h2>
  		<pre>$(cat ${QCDIR}/lnifmri_prep_qcfiles/qc_screen_keyheaders.txt)</pre>
  		<pre>$(cat ${QCDIR}/lnifmri_prep_qcfiles/qc_screen_formattedtable.txt)</pre>
	</div>
  	<div class="column">
  		<h2>List of Excluded Subjects:</h2>
  		<pre>$(cat ${QCDIR}/lnifmri_prep_qcfiles/qc_screen_purgedsubs.txt)</pre>
	</div>
</div>
<br><br><br><br>
</div>

<div id="ACQ" class="tabcontent">
  <h3 style="text-align: center";>Acquisition Parameters</h3>
  <p style="text-align: center";>Breakpoints mark the inconsistency of a given parameter among subjects</p>
<br><br><br>
  <img src="lnifmri_prep_acqparam_QC.png" alt="ACQPars">
<br><br><br><br>
</div>

<div id="MOT" class="tabcontent">
  <h3 style="text-align: center";>Estimation of Motion</h3>
  <p style="text-align: center";>Motion Outliers, In-plane rotations and traslations</p>
<br><br><br>
  <img src="lnifmri_prep_motion_QC.png" alt="MOTPars" class="responsive">
<br><br><br><br>
</div>

<div id="MNI" class="tabcontent">
  <h3 style="text-align: center";>Registration to MNI brain template</h3>
  <p style="text-align: center";>Brief description</p>
<br><br><br>
  $(cat ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostd.txt)
<br><br><br><br>
</div>

<div id="T1w" class="tabcontent">
  <h3 style="text-align: center";>Registration to T1w</h3>
  <p style="text-align: center";>Brief description</p>
<br><br><br>
  $(cat ${QCDIR}/lnifmri_prep_qcfiles/qc_gallery_regtostruc.txt)
<br><br><br><br>
</div>

<div id="PWR" class="tabcontent">
  <h3 style="text-align: center";>Power Spectrum of Timeseries</h3>
  <p style="text-align: center";>Overlay of raw and SD-corrected timeseries</p>
<br><br><br>
  <img src="lnifmri_prep_pspec_QC.png" alt="PSPECdata">
<br><br><br><br>
</div>

<div class="footer">
  <p>LNiF MRI Lab @ CIMeC, UniTN - Via delle Regole 101, Mattarello (TN)</p>
</div>

<script>
function openPage(pageName,elmnt,color) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].style.backgroundColor = "";
  }
  document.getElementById(pageName).style.display = "block";
  elmnt.style.backgroundColor = color;
  elmnt.style.color = "black";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();

window.onscroll = function() {sticknav()};
var navbar = document.getElementById("navbar");
var sticky = navbar.offsetTop;
function sticknav() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky")
  } else {
    navbar.classList.remove("sticky");
  }
}

</script>

</body>
</html> 
EOR

duration=$SECONDS
printf -v exectime "$(($duration / 60))m:$(($duration % 60))s."
NextStep