#!/bin/bash
#
# LNiF MRI Lab Pipeline for preprocessing of
# structural and functional MRI dataset
# stefano.tambalo@unitn.it - 20200310
#
# Generation of utility files and report for visual QC
#
########################################################################
export LC_ALL=C

shopt -s extglob

UsageFSL() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "\tFSLDIR not set!\n\n"
    printf "\tRequires:\n\t\tFSL (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSL)\n"
    printf "\n\n(c) stefano.tambalo@unitn.it, 2020.\n"
    printf "***************************************************\n\n"
    exit 1
}

Start() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "Build QC reports (registration, motion correction, power spectrum)\n"        
}

NextStep() {
    printf "Complete. Exec. Time: ${exectime}\n\n"
	printf "To browse a QC summary of your data, open:\n"    
	printf "file:/%s\n" "`pwd`/lnifmri_prep_report.html"    	
    printf "\n\n***************************************************\n\n"
    exit 1
}

[ "$FSLDIR" = "" ] && UsageFSL
exectime=0
SECONDS=0
pnglist=""
QCDIR=`pwd`/qc
# stamp=`date +'%T'`
stamp=`date +%Y%m%d_%H%M%S`

#legend="fmp,tup,unc"

Start

###############################################################################################	
# Compose summary motion report
for epiimg in `cat lnifmri_prep_inputlist.txt` ; do

    epiname=$($FSLDIR/bin/remove_ext ${epiimg})
    
    readarray -d / -t fileparts <<< "${epiimg}"
    sid=$((${#fileparts[@]}-3))
    subID=$(echo ${fileparts[${sid}]})

	# Compose a single-subject motion report
	rot=${epiname}_rot.png
	tra=${epiname}_tra.png
	mot=${epiname}_motout.png
	# Link 3 motion charts in a single row
	printf -v str  "%s + %s + %s" "$mot" "$tra" "$rot" 
	[[ -z "$pnglist" ]] && pnglist="${pnglist} ${str}" || pnglist="${pnglist} - ${str}"
done

#Create final plot (motion)                       
$FSLDIR/bin/pngappend ${pnglist} ${QCDIR}/lnifmri_prep_qc_motion.png

# ###############################################################################################	
# # Compose summary motion report
# for epiimg in `cat lnifmri_prep_inputlist.txt` ; do

#     epiname=$($FSLDIR/bin/remove_ext ${epiimg})
    
#     readarray -d / -t fileparts <<< "${epiimg}"
#     sid=$((${#fileparts[@]}-3))
#     subID=$(echo ${fileparts[${sid}]})

# 	# printf "${subID}\n" >> ${QCDIR}/qc_screen_subs.txt

# 	rot=${epiname}_rot.png
# 	tra=${epiname}_tra.png

# 	#Compose a single-subject motion report
# 	if [ -f ${epiname}_motout.txt ]; then
# 		mot=${epiname}_motout.png
# 		# Link 3 motion charts in a single row
# 		printf -v str  "%s + %s + %s" "$mot" "$tra" "$rot" 
# 		[[ -z "$pnglist" ]] && pnglist="${pnglist} ${str}" || pnglist="${pnglist} - ${str}"
# 	else
# 		#Create an empty placeholder to keep consistent layout of report
# 		printf "${subID}: Motion outliers not found! Preparing a placeholder\n"
# 		k=$($FSLDIR/bin/fslval ${epiimg} dim4)
# 		awk -v i=$k 'BEGIN { OFS="0\n"; $i="0"; print }' > ${subID}/func/placeholder_motout.txt
# 		$FSLDIR/bin/fsl_tsplot	-i ${subID}/func/placeholder_motout.txt \
# 								-t 'Motion Outliers not detected' \
# 								-a out,dvars -w 660 -h 220 \
# 								--ymin=0 --ymax=100 \
# 								-o ${subID}/func/placeholder_motout.png;
# 		mot=${subID}/func/placeholder_motout.png
# 		printf -v str  "%s + %s + %s" "$mot" "$tra" "$rot" 
# 		[[ -z "$pnglist" ]] && pnglist="${pnglist} ${str}" || pnglist="${pnglist} - ${str}"
# 	fi
# done

# # paste -d " " `ls -d1 $(pwd)/sub*/func/*_motout.txt` > ${QCDIR}/qc_motion_motout.txt	
# # # Merge motion outliers temporal masks and plot a group report
# # awk '{for(i=1;i<=NF;i++)x+=$i;print x;x=0}' $QCDIR/qc_motion_motout.txt > $QCDIR/qc_motion_motout_sum.txt
# # $FSLDIR/bin/fsl_tsplot	-i $QCDIR/qc_motion_motout_sum.txt\
# # 							-t 'Summary of Motion Outliers'\
# # 							-a sum -w 640 -h 144 \
# # 							-o $QCDIR/qc_summary_motout.png;
# # pnglist="$pnglist ${QCDIR}/qc_summary_motout.png"

# #Create final plot (motion)                       
# $FSLDIR/bin/pngappend ${pnglist} ${QCDIR}/lnifmri_prep_qc_motion.png

###############################################################################################
# Compose summary power spectra report

for subID in `cat ${QCDIR}/qc_screen_subs_uniq.txt` ; do
	speclist=$(ls -d1 ${subID}/func/sdc_unc/*-spectra.png)
	pslist=""
	# In case there is only TASK data	
	if [ -z "$speclist" ]; then
		printf "${subID}: Power spectra not found!\n"		
	else
		for ps in $speclist ; do
			printf "${subID}: ${ps}\n"		

	   		[[ -z "$pslist" ]] && pslist="${pslist} ${ps}" || pslist="${pslist} + ${ps}"
	 	done
	 	
	 	$FSLDIR/bin/pngappend ${pslist} ${QCDIR}/qc_pspec_${subID}.png
	fi
done

#Create final plot (power spectrum)
printf -v pspeclist "$( ls -d1 ${QCDIR}/qc_pspec_sub*.png | sed ':a;N;$!ba;s/\n/ - /g' )"
$FSLDIR/bin/pngappend ${pspeclist} $QCDIR/lnifmri_prep_qc_pspec.png

# ###############################################################################################
# # Compose summary power spectra report

# for subID in `cat ${QCDIR}/qc_screen_subs_uniq.txt` ; do
# 	speclist=$(ls -d1 ${subID}/func/sdc_unc/*-spectrum.txt)
	
# 	# In case there is only TASK data	
# 	if [ -z "$speclist" ]; then

# 		printf "${subID}: Power spectrum not found!\n"		

# 	else
# 		# Merge spectra files and plot a subject-wise overlay
# 	    paste -d " " ${speclist} > ${QCDIR}/qc_${subID}_pspectra.txt
# 		# Number of spectra available
# 		last=$(awk '{print NF; exit}' $QCDIR/qc_${subID}_pspectra.txt)
# 		# Plot a chart for each spectrum
# 		for i in $(seq 1 ${last}) ; do
# 			printf -v sesID "ses-%02d" "${i}"	
# 			TR=$($FSLDIR/bin/fslval ${subID}/func/sdc_unc/${subID}_${sesID}_bold_rest.nii.gz pixdim4)	
# 			dim=$(cat $QCDIR/qc_${subID}_pspectra.txt | wc -l )
# 			nyq=$(echo "0.5/${TR}/${dim}" | bc -l )
# 			printf -v psout "${QCDIR}/qc_${subID}_${sesID}_pspec.png"

# 			$FSLDIR/bin/fsl_tsplot  -i $QCDIR/qc_${subID}_pspectra.txt \
# 									-u ${nyq} \
# 		 							-y "Power" -x "Frequency (Hz)" \
# 			                  	    -t "${subID} GMw Power Spectra (SD-uncorrected data)" \
# 		 	   	                    -a ${sesID} -w 660 -h 220 \
# 		 	   	                    --ymin=0 --ymax=1e+6 \
# 		 	   	                    --start=${i} --finish=${i} \
# 		 	       		            -o ${psout};

# 	   		[[ -z "$pslist" ]] && pslist="${pslist} ${psout}" || pslist="${pslist} - ${psout}"
# 	 	done

# 	 	$FSLDIR/bin/pngappend ${pslist} ${QCDIR}/qc_pspec_${subID}.png
# 	fi
# done

# #Create final plot (power spectrum)
# printf -v pspeclist "$( ls -d1 ${QCDIR}/qc_pspec_sub*.png | sed ':a;N;$!ba;s/\n/ + /g' )"
# $FSLDIR/bin/pngappend ${pspeclist} $QCDIR/lnifmri_prep_qc_pspec.png


###############################################################################################
# Compose summary SDC methods available for subID
# Update labels in case some options are missing (FMP, TUP or both)
for subID in `cat ${QCDIR}/qc_screen_subs_uniq.txt` ; do
	fs="fmp,"
	ts="tup,"
	us="unc"

	if [ ! -d ${subID}/func/sdc_fmp ]; then
		fs="---,"
	fi
	if [ ! -d ${subID}/func/sdc_tup ]; then
		ts="---,"
	fi
	printf "(Avail. SDC: %s)\n" "${fs}${ts}${us}" >> ${QCDIR}/qc_report_sdc.txt
done #for subID

###############################################################################################
# Create filelist for group-ICA in MNI space
ls -d1 `pwd`/sub*/func/sdc_fmp/*MNI-smooth.nii.gz > $QCDIR/filelist-groupICA-fmp.txt
ls -d1 `pwd`/sub*/func/sdc_tup/*MNI-smooth.nii.gz > $QCDIR/filelist-groupICA-tup.txt
ls -d1 `pwd`/sub*/func/sdc_unc/*MNI-smooth.nii.gz > $QCDIR/filelist-groupICA-unc.txt

###############################################################################################
# Create some utility files for the HTML report

cp ${QCDIR}/qc_screen_keyheaders.txt 		${QCDIR}/lnifmri_prep_qc_report_keyheaders.txt
cp ${QCDIR}/qc_screen_formattedtable.txt 	${QCDIR}/lnifmri_prep_qc_report_formattedtable.txt
cp ${QCDIR}/qc_screen_purgedscans.txt 		${QCDIR}/lnifmri_prep_qc_report_purgedscans.txt

# Input list with SDC info
paste -d " " ${QCDIR}/qc_screen_subs_uniq.txt ${QCDIR}/qc_screen_sdc.txt > ${QCDIR}/lnifmri_prep_qc_report_subssdc.txt

# Conversion list raw subj-name -> sub-XX
printf "%s ->\n" `ls -d1 ../*.sub` > ${QCDIR}/qc_screen_rawsubs.txt
paste ${QCDIR}/qc_screen_rawsubs.txt ${QCDIR}/qc_screen_subs_uniq.txt > ${QCDIR}/lnifmri_prep_qc_report_rawtosubs.txt

# List to populate registration gallery to std
ls -d1 ${QCDIR}/lnifmri_prep_func2std_QC/*sub-*.png > ${QCDIR}/qc_gallery_regtostd_images.txt
for s in `cat ${QCDIR}/qc_gallery_regtostd_images.txt`; do
	case "${s}" in
		*fmap*)
			printf "%s(fmp)\n" `grep -oP "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/qc_gallery_regtostd_captions.txt
		;;
		*tup*)
			printf "%s(tup)\n" `grep -oP "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/qc_gallery_regtostd_captions.txt
		;;
		*unc*)
			printf "%s(unc)\n" `grep -oP "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/qc_gallery_regtostd_captions.txt
		;;
	esac
done
paste -d "|" ${QCDIR}/qc_gallery_regtostd_images.txt ${QCDIR}/qc_gallery_regtostd_captions.txt > ${QCDIR}/qc_gallery_regtostd_media.txt
awk	-F \| '
	{printf "<div class=\"container\">\n\t<img src=\"%s\" alt=\"Reg2Std\" class=\"responsive\">\n\t<div class=\"top-left\">%s</div>\n</div>\n", $1, $2}' \
	${QCDIR}/qc_gallery_regtostd_media.txt > ${QCDIR}/lnifmri_prep_qc_report_regtostd.txt

# List to populate registration gallery to struc 
ls -d1 ${QCDIR}/lnifmri_prep_func2struc_QC/*sub-*.png > ${QCDIR}/qc_gallery_regtostruc_images.txt
for s in `cat ${QCDIR}/qc_gallery_regtostruc_images.txt`; do
	case "${s}" in
		*fmap*)
			printf "%s(fmp)\n" `grep -oP -m 1 "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/qc_gallery_regtostruc_captions_temp.txt
		;;
		*tup*)
			printf "%s(tup)\n" `grep -oP -m 1 "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/qc_gallery_regtostruc_captions_temp.txt
		;;
		*unc*)
			printf "%s(unc)\n" `grep -oP -m 1 "sub-[0-9][0-9]" <<< ${s}` >>  ${QCDIR}/qc_gallery_regtostruc_captions_temp.txt
		;;
	esac
done
uniq ${QCDIR}/qc_gallery_regtostruc_captions_temp.txt > ${QCDIR}/qc_gallery_regtostruc_captions.txt
paste -d "|" ${QCDIR}/qc_gallery_regtostruc_images.txt ${QCDIR}/qc_gallery_regtostruc_captions.txt > ${QCDIR}/qc_gallery_regtostruc_media.txt
awk	-F \| '
	{printf "<div class=\"container\">\n\t<img src=\"%s\" alt=\"Reg2Std\" class=\"responsive\">\n\t<div class=\"top-left\">%s</div>\n</div>\n", $1, $2}' \
	${QCDIR}/qc_gallery_regtostruc_media.txt > ${QCDIR}/lnifmri_prep_qc_report_regtostruc.txt

###############################################################################################
# Create an HTML report
cat << EOR > ${QCDIR}/lnifmri_prep_report.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box}

body, html {
  height: 100%;
  margin: 0;
  font-family: "Courier New", Courier, monospace;
}

.header {
  padding: 20px;
  text-align: center;
  background: #555;
  color: white;
  font-size: 24px;
}

img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}

#navbar {
  overflow: hidden;
  background-color: #555;
}

.sticky {
  position: fixed;
  top: 0;
  width: 100%;
}

.content {
  padding: 16px;
}

.sticky + .content {
  padding-top: 60px;
}

.tablink {
  background-color: #555;
  color: white;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  font-size: 18px;
  width: 16.66%;
  display: table-cell;
}

.tablink:hover {
  background-color: #777;
}

.tabcontent {
  color: black;
  display: none;
  padding: 20px 20px;
  padding-top: 50px;
  height: 100%;
}

.responsive {
	width: 100%;
	height: auto;
}

.footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: #555;
  color: white;
  text-align: center;
}

.column {
  float: left;
  width: 50%;
  padding: 25px 100px 50px;
  margin: auto;
}

.row:after {
  content: "";
  display: table;
  clear: both;
}

@media screen and (max-width: 600px) {
  .column {
    width: 100%;
  }

.container {
  display: flex;
  flex-wrap: wrap;
  padding: 0 4px;
  position: relative;
  text-align: center;
  color: white;
  background-color: white;

}

/* Top left text */
.top-left {
  position: absolute;
  top: 8px;
  left: 16px;
}

/* Solid border */
hr.solid {
  border-top: 3px solid #555;
}

</style>
</head>
<body>

<div class="header">
  <h1>lnifmri_prep</h1>
  <p>Quality Control Report</p>
</div>

<div id="navbar">
<button class="tablink" onclick="openPage('REP', this, 'white')" id="defaultOpen">REPORT</button>
<button class="tablink" onclick="openPage('ACQ', this, 'white')">ACQP</button>
<button class="tablink" onclick="openPage('MNI', this, 'white')">MNI</button>
<button class="tablink" onclick="openPage('T1w', this, 'white')">T1w</button>
<button class="tablink" onclick="openPage('MOT', this, 'white')">MOTCO</button>
<button class="tablink" onclick="openPage('PWR', this, 'white')">PWR</button>
</div>

<!--
<hr class="solid">
-->

<div id="REP" class="tabcontent">
<br>
  <p style="text-align: center;"><b>Output dir</b>: $(pwd); <b>Timestamp</b>: ${stamp}</p>
 <br>
 <div class="row">
 	<div class="column">
  		<h2>List of Available Subjects:</h2>
  		<pre>$(cat ${QCDIR}/lnifmri_prep_qc_report_rawtosubs.txt)</pre>
	</div>
  	<div class="column">
  		<h2>List of Processed Subjects:</h2>
  		<pre>$(cat ${QCDIR}/lnifmri_prep_qc_report_subssdc.txt)</pre>
	</div>
 </div>
 <div class="row">
  	<div class="column">
  		<h2>Summary of Acq. Parameters:</h2>
  		<pre>$(cat ${QCDIR}/lnifmri_prep_qc_report_keyheaders.txt)</pre>
  		<pre>$(cat ${QCDIR}/lnifmri_prep_qc_report_formattedtable.txt)</pre>
	</div>
  	<div class="column">
  		<h2>List of Excluded Scans (Code):</h2>
  		<pre>$(cat ${QCDIR}/lnifmri_prep_qc_report_purgedscans.txt)</pre>
	</div>
</div>
<br><br><br><br>
</div>

<div id="ACQ" class="tabcontent">
  <h3 style="text-align: center";>Acquisition Parameters</h3>
  <p style="text-align: center";></p>
<br><br><br>
  <img src="lnifmri_prep_qc_acqpars.png" alt="ACQPars">
<br><br><br><br>
</div>

<div id="MOT" class="tabcontent">
  <h3 style="text-align: center";>Estimation of Motion</h3>
  <p style="text-align: center";>Motion Outliers, In-plane translations and rotations</p>
<br><br><br>
  <img src="lnifmri_prep_qc_motion.png" alt="MOTPars" class="responsive">
<br><br><br><br>
</div>

<div id="MNI" class="tabcontent">
  <h3 style="text-align: center";>Registration to MNI brain template</h3>
  <p style="text-align: center";>Functional EPI to Standard Space Template</p>
<br><br><br>
  $(cat ${QCDIR}/lnifmri_prep_qc_report_regtostd.txt)
<br><br><br><br>
</div>

<div id="T1w" class="tabcontent">
  <h3 style="text-align: center";>Registration to T1w</h3>
  <p style="text-align: center";>Functional EPI to Subject Space Anatomical Scan</p>
<br><br><br>
  $(cat ${QCDIR}/lnifmri_prep_qc_report_regtostruc.txt)
<br><br><br><br>
</div>

<div id="PWR" class="tabcontent">
  <h3 style="text-align: center";>Power Spectrum of Timeseries</h3>
  <p style="text-align: center";>Overlay of raw and BPF, SD-uncorrected timeseries</p>
<br><br><br>
  <img src="lnifmri_prep_qc_pspec.png" alt="PSPECdata">
<br><br><br><br>
</div>

<div class="footer">
  <p>LNiF MRI Lab @ CIMeC, UniTN - Via delle Regole 101, Mattarello (TN)</p>
</div>

<script>
function openPage(pageName,elmnt,color) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].style.backgroundColor = "";
  }
  document.getElementById(pageName).style.display = "block";
  elmnt.style.backgroundColor = color;
  elmnt.style.color = "black";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();

window.onscroll = function() {sticknav()};
var navbar = document.getElementById("navbar");
var sticky = navbar.offsetTop;
function sticknav() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky")
  } else {
    navbar.classList.remove("sticky");
  }
}

</script>

</body>
</html> 
EOR

# ###############################################################################################
# # Clean up QC folder
# mkdir -p $QCDIR/lnifmri_prep_qcfiles
# mv $QCDIR/qc_*.txt $QCDIR/lnifmri_prep_qcfiles/
# mv $QCDIR/qc_*.png $QCDIR/lnifmri_prep_qcfiles/

# ###############################################################################################
# # Clean up subID folders 
# for sID in `cat ${QCDIR}/lnifmri_prep_qcfiles/qc_screen_subs_uniq.txt`; do
# 	mkdir -p ${sID}/func/lnifmri_prep_files
# 	ls -d1 ${sID}/func/*.* > ${sID}/func/${sID}_filelist.txt
# 	xargs mv -t ${sID}/func/lnifmri_prep_files/ < ${sID}/func/${sID}_filelist.txt
# done

duration=$SECONDS
printf -v exectime "$(($duration / 60))m:$(($duration % 60))s."
NextStep