#!/bin/bash
#
# LNiF MRI Lab Pipeline for preprocessing of
# structural and functional MRI dataset
# stefano.tambalo@unitn.it - 20200310
#
# Preprocess functional EPI timeseries:
# -   Drop 10 volumes
# -   Grand Mean Scaling
# -   Realignment and estimation of motion parameters
# -   Detection of motion outliers for temporal masking
#
########################################################################
export LC_ALL=C

shopt -s extglob
Usage() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "\tFSLDIR not set!\n\n"
    printf "\tRequires:\n\t\tFSL (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSL)\n"
    printf "\n\n(c) stefano.tambalo@unitn.it, 2020.\n"
    printf "***************************************************\n\n"
    exit 1
}

Start() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "Process functional data (motion correction)\n"    

}

NextStep() {
    printf "\n***************************************************\n"
    printf "LNiF MRI Lab Preprocessing Pipeline\n"
    printf "CIMeC - Center for Mind/Brain Science\n\n"
    printf "Complete. Exec. Time: ${exectime}\nNow run lnifmri_prep03_sdc"
    printf "\n\n***************************************************\n\n"
    exit 1
}

[ "$FSLDIR" = "" ] && Usage
exectime=0
SECONDS=0

Start

for SUBDIR in sub-*[0-9] ; do
#cd ${subdir}
#echo $SUBDIR
    for epiimg in `$FSLDIR/bin/imglob $SUBDIR/func/*ep2d_bold*[0-9]_+([0-9]).nii.gz` ; do

        epiname=`$FSLDIR/bin/remove_ext ${epiimg}`
        # scanname=`basename ${epiimg}`

        printf "\tDataset: ${epiname}\n"

        printf "\tReformat JSON file\n"
        cat ${epiname}.json | tr -d '\n' > ${epiname}_temp1.json
        sed 's/,\t"/,\n"/g' ${epiname}_temp1.json > ${epiname}_temp2.json
        cat ${epiname}_temp2.json | tr -d '\t' > ${epiname}_parameters.json

        #Store multiband slice timing extracted from JSON
        awk '$1 ~ /"SliceTiming"/ {print $2}' ${epiname}_parameters.json >> ${epiname}_temp_slicetiming.json
        cat ${epiname}_temp_slicetiming.json | tr ',[]' '\n' > ${epiname}_slicetiming.txt

        
        #Extract core parameters from JSON
        # TR=$(cat ${epiname}.json | sed 's/.*"RepetitionTime": \(.*\),.*/\1/;t;d')
        TR=$(awk '$1 ~ /"RepetitionTime"/ {print $2}' ${epiname}_parameters.json | tr -d ',')

        # echo "TR: ${TR}"

        #Store multiband slice timing extracted from JSON
        # cat ${epiname}.json | \
        # tr -d '\n\t' | \
        # sed 's/.*"SliceTiming": \[\([^]]*\)\].*/\1/g' | \
        # tr ',' '\n' > $SUBDIR/func/${scanname}_slicetiming.txt;
        # awk '/SliceTiming: \[/,/\]/' {epiname}.json | tr -d '[A-z:]' >> $SUBDIR/func/${scanname}_slicetiming.txt

        #Next steps are self-explanatory
        printf "\tDiscarding first 10 vols\n"
        $FSLDIR/bin/fslroi $epiimg $epiimg 10 150

        printf "\tSetting data type\n"
        $FSLDIR/bin/fslmaths $epiimg $epiimg -odt float 

        printf "\tGrand Mean scaling\n"
        $FSLDIR/bin/fslmaths $epiimg -ing 1000 $epiimg

        printf "\tSlice Timing correction\n"
        $FSLDIR/bin/slicetimer  -i $epiimg \
                                -o $epiimg \
                                --odd -r $TR \
                                --tcustom=${epiname}_slicetiming.txt;

        printf "\tMotion Correction\n"
        $FSLDIR/bin/mcflirt -in $epiimg \
                            -out $epiimg \
                            -meanvol \
                            -mats -plots \
                            -rmsrel -rmsabs \
                            -spline_final;
        #Plot motion traces
        $FSLDIR/bin/fsl_tsplot  -i ${epiname}.par \
                                -t 'MCFLIRT estimated rotations (radians)' \
                                -u 1 --start=1 --finish=3 -a x,y,z -w 640 -h 144 \
                                --ymin=-0.01 --ymax=0.01 \
                                -o ${epiname}_rot.png;
        #Plot motion traces
        $FSLDIR/bin/fsl_tsplot  -i ${epiname}.par \
                                -t 'MCFLIRT estimated translations (mm)' \
                                --ymin=-1 --ymax=1 \
                                -u 1 --start=4 --finish=6 -a x,y,z -w 640 -h 144 \
                                -o ${epiname}_tra.png;

        printf "\tDetecting motion outliers\n\n"
        $FSLDIR/bin/fsl_motion_outliers -i $epiimg \
                                        -o ${epiname}_motout.txt \
                                        -s ${epiname}_motoutdvars.txt \
                                        --dvars --nomoco;
        #Plot motion traces
        $FSLDIR/bin/fsl_tsplot  -i ${epiname}_motoutdvars.txt \
                                -t 'Motion Outlier Metric: dvars' \
                                -a out -w 640 -h 144 \
                                --ymin=0 --ymax=100 \
                                -o ${epiname}_motout.png;                                    
    done #${epiname}
done #for .sub
duration=$SECONDS
printf -v exectime "$(($duration / 60))m:$(($duration % 60))s."
NextStep